[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
calc_dapp = "DjuK45k5jZr1nd242qEiaeaRmZXGMTdaGdWZsrZLqeMo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tiagodavi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
